config/routes.rb
Rails.application.routes.draw do
  resources :edienkartes
  get 'lietotajaparametrs/activatepython'
  get 'velprods/test'
  get 'nevelprods/adding'
  get 'edienkartes/tested'
  get 'bazesprods/product'
  resources :bazesprods
  resources :velprods
  resources :nevelprods
  resources :lietotajaparametrs
  devise_for :users, controllers: { registrations: "registrations" }
  root 'lietotajaparametrs#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lietotajaparametr.rb
class Lietotajaparametr < ApplicationRecord
  belongs_to :user
  validates :user_id, uniqueness: true
  validates :svars, presence: true, format: { with: /\A([1-9]\d\d?)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :augums, presence: true, format: { with: /\A([1-9]\d|[1-2]\d\d)\Z/, message: '- Ievadiet tikai vienu veselo skaitli' }
  validates :vecums, presence: true, format: { with: /\A([1-9]|[1-9]\d|[1-9]\d\d)\Z/, message: '- Ievadiet tikai vienu veselo skaitli' }

  enum koef: {
    "Neaktīvs (sēdošs dzīvesveids, fiziskas aktivitātes ar mazu intensitāti vai vispār nav)" => 1.2,
    "Mazāk aktīvs (vieglas fiziskas aktivitātes 1-3 reizes nedēļā)" => 1.3,
    "Vidēji aktīvs (vidēji sarežģīts fizisks darbs vai fiziskas aktivitātes ar vidēju intensitāti 3-5 reizes nedēļā)" => 1.5,
    "Vairāk aktīvs (fizisks darbs un fiziskas nodarbības, vai tikai intensīvas nodarbības 6-7 reizes nedēļā)" => 1.7,
    "Ļoti aktīvs (fizisks darbs un ļoti intensīvas sporta nodarbības)"=> 1.9
  }

  enum goal: {
    'Tagadējā svara saglabāšana' => 0,
    'Samazināt svaru' => 1,
    'Muskulatūras palielināšana' => 2,
    'Svara samazināšana un muskulatatūras palielināšana' => 3,
    'Masas palielināšana' => 4
  }

  enum dzimums: {
    'Sieviešu' => 'S',
    'Vīriešu' => 'V'
  }

end

app/controllers/lietotajaparametrs_controller.rb
class LietotajaparametrsController < ApplicationController
  before_action :set_lietotajaparametr, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  # GET /lietotajaparametrs or /lietotajaparametrs.json
  def index
    @lietotajaparametrs = Lietotajaparametr.all

  end

  # GET /lietotajaparametrs/1 or /lietotajaparametrs/1.json
  def show
  end

  # GET /lietotajaparametrs/new
  def new
    @type = "new"
    if Lietotajaparametr.exists?(user_id: current_user.id)
      redirect_to lietotajaparametrs_path, notice: "Nav piekļuves"
    else
      @lietotajaparametr = current_user.lietotajaparametrs.build
    end
  end

  # GET /lietotajaparametrs/1/edit
  def edit
    @type = "edit"

  end

  # POST /lietotajaparametrs or /lietotajaparametrs.json
  def create
    @lietotajaparametr = current_user.lietotajaparametrs.build(lietotajaparametr_params)


    respond_to do |format|
      if @lietotajaparametr.save
        format.html { redirect_to lietotajaparametrs_url, notice: "Jūsu parametri ir veiksmīgi saglabāti." }
        format.json { render :show, status: :created, location: @lietotajaparametr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lietotajaparametr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lietotajaparametrs/1 or /lietotajaparametrs/1.json
  def update
    respond_to do |format|
      if @lietotajaparametr.update(lietotajaparametr_params)
        format.html { redirect_to lietotajaparametrs_url, notice: "Jūsu parametri ir veiksmīgi atjaunināti." }
        format.json { render :show, status: :ok, location: @lietotajaparametr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lietotajaparametr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lietotajaparametrs/1 or /lietotajaparametrs/1.json
  def destroy
    @lietotajaparametr.destroy
    respond_to do |format|
      format.html { redirect_to lietotajaparametrs_url, notice: "Jūsu parametri ir veiksmīgi dzēsti." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @lietotajaparametr = current_user.lietotajaparametrs.find_by(id: params[:id])
    redirect_to lietotajaparametrs_path, notice: "Nav tiesību rediģēt" if @lietotajaparametr.nil?
  end

  def activatepython

    edienkarte = Edienkarte.where(user_id: current_user.id).all
    unless edienkarte.nil?
      edienkarte.delete_all
    end
    Dir.chdir(Rails.root)
    system "python3 lib/assets/Dieta2.py '#{current_user.id}' "
    @edienkartes = edienkarte
    @average_price = average_price(edienkarte)
  end

  def average_price(edienkarte)
    bazesprods = Bazesprod.all
    average_price = 0
    edienkarte.each do |product|
      if bazesprods.exists?(prodnos: product.prodnos)
        full_price = bazesprods.where(prodnos: product.prodnos).first&.cena.to_f
        average_prod_price = full_price / 100 * product.quantity.to_i
        average_price += average_prod_price

      else
        full_price = product.cena.to_f
        average_price += full_price
      end
    end
    average_price.round(2)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lietotajaparametr
      @lietotajaparametr = Lietotajaparametr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lietotajaparametr_params
      params.require(:lietotajaparametr).permit(:svars, :augums, :vecums, :dzimums, :user_id, :koef, :goal)
    end
end

app/helpers/lietotajaparametrs_helper.rb
module LietotajaparametrsHelper
end

app/views/lietotajaparametrs/_form.html.erb
<%= form_with(model: lietotajaparametr) do |form| %>
  <% if lietotajaparametr.errors.any? %>
    <div id="error_explanation">
      <h2><%= I18n.t('errors.template.header', count: lietotajaparametr.errors.count) %></h2>

      <ul>
        <% lietotajaparametr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-4">
      <div class="form-control">
        <div class="field">
          <%= form.label :svars, class: "form-label" %>
          <div class="input-group" >
            <%= form.number_field :svars, step: :any, class: "form-control", required: true %>
            <span class="input-group-text">kg</span>
          </div>
        </div>

        <div class="field">
          <%= form.label :augums, class: "form-label" %>
          <div class="input-group" >
          <%= form.number_field :augums, class: "form-control", required: true %>
            <span class="input-group-text">cm</span>
          </div>
        </div>

        <div class="field">
          <%= form.label :vecums, class: "form-label" %>
          <div class="input-group" >
            <%= form.number_field :vecums, class: "form-control", required: true %>
            <span class="input-group-text">gadi</span>
          </div>
        </div>

        <div class="field">
          <%= form.label :dzimums, class: "form-label" %>
          <%= form.select :dzimums, options_for_select([['Sieviešu'], ['Vīriešu']]), { } ,class: "form-select"  %>
        </div>

        <div class="field">
          <% form.label :user_id %>
          <%= form.number_field :user_id, id: :lietotajaparametrs_user_id, value: current_user.id, type: :hidden  %>
        </div>

        <div class="field">
          <%= form.label I18n.t(:koef), class: "form-label" %>
          <%= form.select :koef, options_for_select([['Neaktīvs (sēdošs dzīvesveids, fiziskas aktivitātes ar mazu intensitāti vai vispār nav)'], ['Mazāk aktīvs (vieglas fiziskas aktivitātes 1-3 reizes nedēļā)'], ['Vidēji aktīvs (vidēji sarežģīts fizisks darbs vai fiziskas aktivitātes ar vidēju intensitāti 3-5 reizes nedēļā)'], ['Vairāk aktīvs (fizisks darbs un fiziskas nodarbības, vai tikai intensīvas nodarbības 6-7 reizes nedēļā)'], ['Ļoti aktīvs (fizisks darbs un ļoti intensīvas sporta nodarbības)']]), {},class: "form-select"  %>
        </div>

        <div class="field">
          <%= form.label "Mērķis", class: "form-label" %>
          <%= form.select :goal, options_for_select([['Tagadējā svara saglabāšana'],['Samazināt svaru'], ['Muskulatūras palielināšana'], ['Svara samazināšana un muskulatatūras palielināšana'], ['Masas palielināšana']]), {}, class: "form-select" %>
        </div>
        <br/>
        <% if @type=="edit" %>
          <% submit_name = "Atjaunināt" %>
        <% else submit_name = "Pievienot"%>
        <% end %>
        <div class="row justify-content-between">
          <div class="col">
            <%= link_to 'Atpakaļ', lietotajaparametrs_path,class: "btn btn-secondary" %>
          </div>
          <div class="col-4">
              <%= form.submit submit_name, class: "btn btn-primary" %>
            <br/><br/>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/lietotajaparametrs/activatepython.html.erb
<div class="row justify-content-around">
  <div class="col-4">
    <div class="card" style="width: 24rem;">
      <div class="card-body">
        <h1 class="card-title">Jūsu ēdienkarte</h1>
        <table class="table table-striped table-hover">
          <thead>
            <tr>

              <th><%= I18n.t(:prodnos) %></th>
              <th><%= I18n.t(:quantity) %></th>
            </tr>

          </thead>
          <tbody>
            <% @edienkartes.each do |edienkarte| %>
              <% if current_user == edienkarte.user %>
                <% cache edienkarte do %>
                  <tr>
                    <td><%= edienkarte.prodnos %></td>
                    <td><%= edienkarte.quantity %> g</td>
                    <td><%= link_to('Apskatīt', edienkartes_tested_path(edienkarte.id), class: "btn btn-dark btn-sm")%></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>

          </tbody>

        </table>
        <h5> Vidējā ēdienkartes cena: <%= @average_price %> €</h5>

      </div>
      <%= link_to 'Uz galveni', lietotajaparametrs_path, class: "btn btn-secondary" %>

    </div>

  </div>

</div>



<br/>
<br/>
<br>

app/views/lietotajaparametrs/edit.html.erb
<h1>Parametru rediģēšana</h1>

<%= render 'form', lietotajaparametr: @lietotajaparametr %>

app/views/lietotajaparametrs/index.html.erb
<div class="container">
  <div class="row justify-content-around">
    <div class="col-4">
      <div class="card" style="width: 24rem;">
        <div class="card-body">
          <h1 class="card-title">Jūsu parametri</h1>
            <table class="table table-striped table-hover">
              <thead></thead>
              <tbody>
                <% @lietotajaparametrs.each do |lietotajaparametr| %>
                <% if current_user == lietotajaparametr.user %>
                <tr>
                  <td><strong>Svars:</strong></td>
                  <td><%= lietotajaparametr.svars %> kg</td>

                </tr>
                <tr>
                  <td><strong>Dzimums:</strong></td>
                  <td><%= lietotajaparametr.dzimums %></td>

                </tr>
                <tr>
                  <td><strong>Augums:</strong></td>
                  <td><%= lietotajaparametr.augums %> cm</td>

                </tr>
                <tr>
                  <td><strong>Vecums:</strong></td>
                  <td><%= lietotajaparametr.vecums %> gadi</td>


                </tr>
                <tr>
                  <td><strong>Dzīvesveids:</strong></td>
                  <td><%= lietotajaparametr.koef %></td>

                </tr>
                <tr>
                  <td><strong>Mērķis:</strong></td>
                  <td><%= lietotajaparametr.goal %></td>
                </tr>
              </tbody>
            </table>
            <%= link_to 'Rediģēt parametrus', edit_lietotajaparametr_path(lietotajaparametr), class: 'btn btn-primary' %>
                <% end %>
              <% end %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <% if Lietotajaparametr.exists?(user_id: current_user.id) %>
        <div class="card" style="width: 20rem;">
          <div class="card-body">
            <h1 class="card-title">Izvēlne</h1>
            <table class="table">
              <thead></thead>
              <tbody><td> </td></tbody>
            </table>
          </div>
        <% end %>
        <% if Lietotajaparametr.exists?(user_id: current_user.id) %>
        <table class="table">
          <tbody><td><h6><center>Ir pieejams bāzes produktu saraksts, taču Jūs varat pievienot savus produktus un izvēlēties nevēlamos produktus</center></h6>
          </td></tbody>
        </table>
        <% end %>
          <%# shows button if dumb user closed parameter creating page during registration %>

          <br/>
          <% unless Lietotajaparametr.exists?(user_id: current_user.id) %>
        <%= link_to 'Pievienot parametrus', 'lietotajaparametrs/new', class: "btn btn-secondary" %>
            <br/>
          <%  end %>


          <%# --------------------------------------------------------------------------------- %>
        <%# shows button only if dumb user didnt close 'parameter creating page' during registration %>

        <% if Lietotajaparametr.exists?(user_id: current_user.id) %>
          <br/>
          <%= link_to 'Nevēlamie produkti', 'nevelprods#index', class: "btn btn-secondary" %>
          <br/>
          <br/>
          <%= link_to 'Pievienot vai rediģēt produktu', 'velprods#index', class: "btn btn-secondary" %>
          <br/>
          <br/>




            <%= link_to 'Izveidot un apskatīt ēdienkarti', lietotajaparametrs_activatepython_path, class: "btn btn-primary" %>

          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/lietotajaparametrs/new.html.erb
<h1>Jaunie parametri</h1>

<%= render 'form', lietotajaparametr: @lietotajaparametr %>

app/views/lietotajaparametrs/show.html.erb
<p>
  <strong>Svars:</strong>
  <%= @lietotajaparametr.svars %>
</p>

<p>
  <strong>Augums:</strong>
  <%= @lietotajaparametr.augums %>
</p>

<p>
  <strong>Vecums:</strong>
  <%= @lietotajaparametr.vecums %>
</p>

<p>
  <strong>Dzimums:</strong>
  <%= @lietotajaparametr.dzimums %>
</p>

<p>
  <strong>User:</strong>
  <%= @lietotajaparametr.user_id %>
</p>

<%= link_to 'Edit', edit_lietotajaparametr_path(@lietotajaparametr) %> |