config/routes.rb
Rails.application.routes.draw do
  resources :edienkartes
  get 'lietotajaparametrs/activatepython'
  get 'velprods/test'
  get 'nevelprods/adding'
  get 'edienkartes/tested'
  get 'bazesprods/product'
  resources :bazesprods
  resources :velprods
  resources :nevelprods
  resources :lietotajaparametrs
  devise_for :users, controllers: { registrations: "registrations" }
  root 'lietotajaparametrs#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bazesprod.rb
class Bazesprod < ApplicationRecord
  validates :prodnos, presence: true
  validates :olb, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :tauki, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :oglh, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :kcal, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :A, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :B1, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :B2, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :C, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :Ca, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :P, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :Fe, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :cena, presence: true, format: { with: /\A^\d+(\.\d{1,2})?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :min, format: { with: /\A([1-9]\d*|0)\Z/, message: '- Ievadiet tikai veselo skaitli' }
  validates :max, format: { with: /\A([1-9]\d*)\Z/, message: '- Ievadiet tikai veselo skaitli' }


end

app/controllers/bazesprods_controller.rb
class BazesprodsController < ApplicationController
  before_action :set_bazesprod, only: %i[ show edit update destroy product]
  before_action :admin_user, only: [:edit, :destroy, :new, :update]
  def index
    @bazesprods = Bazesprod.order("prodnos ASC").page(params[:page])
  end


  def product
    @last_page = params[:page]
  end

  def new
    @bazesprod = Bazesprod.new
  end

  def edit
  end

  def create
    @bazesprod = Bazesprod.new(bazesprod_params)
    respond_to do |format|
      if @bazesprod.save
        format.html { redirect_to bazesprods_url, notice: "Bāzes produkts ir veiksmīgi saglabāts." }
        format.json { render :product, status: :created, location: @bazesprod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bazesprod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bazesprods/1 or /bazesprods/1.json
  def update
    respond_to do |format|
      if @bazesprod.update(bazesprod_params)
        format.html { redirect_to bazesprods_url, notice: "Bāzes produkts ir veiksmīgi atjaunināts." }
        format.json { render :product, status: :ok, location: @bazesprod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bazesprod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bazesprods/1 or /bazesprods/1.json
  def destroy
    @bazesprod.destroy
    respond_to do |format|
      format.html { redirect_to bazesprods_url, notice: "Bāzes produkts ir veiksmīgi dzēsts." }
      format.json { head :no_content }
    end
  end

  def admin_user
    if !current_user.admin?
      redirect_to(bazesprods_path, notice: "Nav tiesību izpildīt darbību!")
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bazesprod
      @bazesprod = Bazesprod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bazesprod_params
      params.require(:bazesprod).permit(:prodnos, :olb, :tauki, :oglh, :kcal, :A, :B1, :B2, :C, :Ca, :P, :Fe, :cena, :min, :max)
    end
end

app/helpers/bazesprods_helper.rb
module BazesprodsHelper
end

app/views/bazesprods/_form.html.erb
<%= form_with(model: bazesprod) do |form| %>
  <% if bazesprod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bazesprod.errors.count, "error") %> prohibited this bazesprod from being saved:</h2>

      <ul>
        <% bazesprod.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prodnos %>
    <%= form.text_field :prodnos %>
  </div>

  <div class="field">
    <%= form.label :olb %>
    <%= form.text_field :olb %>
  </div>

  <div class="field">
    <%= form.label :tauki %>
    <%= form.text_field :tauki %>
  </div>

  <div class="field">
    <%= form.label :oglh %>
    <%= form.text_field :oglh %>
  </div>

  <div class="field">
    <%= form.label :kcal %>
    <%= form.text_field :kcal %>
  </div>

  <div class="field">
    <%= form.label :A %>
    <%= form.text_field :A %>
  </div>

  <div class="field">
    <%= form.label :B1 %>
    <%= form.text_field :B1 %>
  </div>

  <div class="field">
    <%= form.label :B2 %>
    <%= form.text_field :B2 %>
  </div>

  <div class="field">
    <%= form.label :C %>
    <%= form.text_field :C %>
  </div>

  <div class="field">
    <%= form.label :Ca %>
    <%= form.text_field :Ca %>
  </div>

  <div class="field">
    <%= form.label :P %>
    <%= form.text_field :P %>
  </div>

  <div class="field">
    <%= form.label :Fe %>
    <%= form.text_field :Fe %>
  </div>

  <div class="field">
    <%= form.label :cena %>
    <%= form.text_field :cena %>
  </div>

  <div class="field">
    <%= form.label :min %>
    <%= form.text_field :min %>
  </div>

  <div class="field">
    <%= form.label :max %>
    <%= form.text_field :max%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bazesprods/edit.html.erb
<h1>Editing Bazesprod</h1>

<%= render 'form', bazesprod: @bazesprod %>

<%= link_to 'Show', @bazesprod %> |
<%= link_to 'Back', bazesprods_path %>

app/views/bazesprods/index.html.erb
<br/>

<div class="row justify-content-around">
  <div class="col-4">
    <div class="card" style="width: 24rem;">
      <div class="card-body">
        <h1 class="card-title">Noklusēts produktu saraksts</h1>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th><%= I18n.t(:prodnos) %></th>
            </tr>

          </thead>
          <tbody>
          <% @bazesprods.each do |bazesprod| %>

            <tr>
              <td><%= bazesprod.prodnos %></td>

              <td><%= link_to('Sīkāk', bazesprods_product_path(id: bazesprod.id, page: @bazesprods.current_page), class: "btn btn-dark btn-sm")%></td>
              <% if current_user&.admin? %>
                <td><%= link_to 'Dzēst', bazesprod, method: :delete, data: { confirm: 'Vai Jūs esat pārliecināti?' }, class: "btn btn-danger btn-sm" %></td>
              <% end %>
            </tr>
              <% end %>

          </tbody>

        </table>

      </div>
      <%= link_to 'Uz galveni', lietotajaparametrs_path, class: "btn btn-secondary" %>

    </div>

  </div>

</div>



<br/>
<br/>
<div class="container-fluid bg-light">
  <div class="col-md-12 text-center">
    <div class="row">
      <div class="col">
      </div>
      <div class="col">
        <div class="container pagination justify-content-center" >
          <%= paginate @bazesprods %>
        </div>
      </div>
      <div class="col">
      </div>
    </div>
  </div>
</div>
<br>

app/views/bazesprods/new.html.erb
<h1>New Bazesprod</h1>

<%= render 'form', bazesprod: @bazesprod %>

<%= link_to 'Back', bazesprods_path %>

app/views/bazesprods/product.html.erb
<div class="row justify-content-around">
  <div class="col-4">
    <div class="card" style="width: 24rem;">
      <div class="card-body">
        <h1 class="card-title"><%= @bazesprod.prodnos %></h1>
        <table class="table table-striped table-hover">
          <thead></thead>
          <tbody>

          <tr>
            <td><strong><%= I18n.t(:olb) %></strong></td>
            <td><%= @bazesprod.olb %> g</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:tauki) %></strong></td>
            <td><%= @bazesprod.tauki %> g</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:oglh) %></strong></td>
            <td><%= @bazesprod.oglh %> g</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:kcal) %></strong></td>
            <td><%= @bazesprod.kcal %> kcal</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:A) %></strong></td>
            <td><%= @bazesprod.A %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:B, num: 1) %></strong></td>
            <td><%= @bazesprod.B1 %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:B, num:2) %></strong></td>
            <td><%= @bazesprod.B2 %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:C) %></strong></td>
            <td><%= @bazesprod.C %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:Ca) %></strong></td>
            <td><%= @bazesprod.Ca %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:P) %></strong></td>
            <td><%= @bazesprod.P %> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:Fe) %></strong></td>
            <td><%= @bazesprod.Fe%> mg</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:cena) %></strong></td>
            <td><%= @bazesprod.cena %> €</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:min) %></strong></td>
            <td><%= @bazesprod.min %> g</td>
          </tr>

          <tr>
            <td><strong><%= I18n.t(:max) %></strong></td>
            <td><%= @bazesprod.max%> g</td>
          </tr>
          </tbody>
        </table>
      </div>
      <%= link_to 'Atpakaļ', bazesprods_path(page: @last_page), class: "btn btn-secondary" %>
    </div>
  </div>
</div>