config/routes.rb
Rails.application.routes.draw do
  resources :edienkartes
  get 'lietotajaparametrs/activatepython'
  get 'velprods/test'
  get 'nevelprods/adding'
  get 'edienkartes/tested'
  get 'bazesprods/product'
  resources :bazesprods
  resources :velprods
  resources :nevelprods
  resources :lietotajaparametrs
  devise_for :users, controllers: { registrations: "registrations" }
  root 'lietotajaparametrs#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nevelprod.rb
class Nevelprod < ApplicationRecord
  belongs_to :user
  validates :prod_nos, presence: true
  validate :product_name_with_id, on: %i[new edit create update]

  def product_name_with_id
    if Nevelprod.exists?(user_id: self.user_id, prod_nos: self.prod_nos) == true
      errors.add("Produkts","ar tādu nosaukumu jau bija pievienots")
    end
  end

end

app/controllers/nevelprods_controller.rb
class NevelprodsController < ApplicationController
  before_action :set_nevelprod, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /nevelprods or /nevelprods.json
  def index
    @nevelprods = Nevelprod.all
    @baze = Bazesprod.order('prodnos ASC').all
  end

  # GET /nevelprods/1 or /nevelprods/1.json
  def show
  end

  # GET /nevelprods/new
  def new
    @nevelprod = current_user.nevelprods.build
    @type = "new"
  end

  # GET /nevelprods/1/edit
  def edit
    @submit_name = "Atjaunināt"
    @type = "edit"
  end

  # POST /nevelprods or /nevelprods.json
  def create
    @nevelprod = current_user.nevelprods.build(nevelprod_params)

    respond_to do |format|
      if @nevelprod.save
        format.html { redirect_to nevelprods_url, notice: "Nevēlamais produkts ir veiksmīgi pievienots!" }
        format.json { render :show, status: :created, location: @nevelprod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nevelprod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nevelprods/1 or /nevelprods/1.json
  def update
    respond_to do |format|
      if @nevelprod.update(nevelprod_params)
        format.html { redirect_to nevelprods_url, notice: "Nevēlamais produkts ir veiksmīgi atjaunināts!" }
        format.json { render :show, status: :ok, location: @nevelprod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nevelprod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nevelprods/1 or /nevelprods/1.json
  def destroy
    @nevelprod.destroy
    respond_to do |format|
      format.html { redirect_to nevelprods_url, notice: "Nevēlamais produkts ir veiksmīgi noņemts!" }
      format.json { head :no_content }
    end
  end

  def adding
    if params[:tocopy] != "" and params[:tocopy].to_i != 0  #defense from sql injection
      if !Bazesprod.exists?(params[:tocopy])
        redirect_to nevelprods_path, notice: "Jāievada eksistējošais produkts"
      else
        if Nevelprod.exists?(prod_nos: Bazesprod.where(id: params[:tocopy]).first.prodnos, user_id: current_user.id)
          redirect_to nevelprods_path, notice: "Izvēlētais produkts jau ir pievienots"
        else
          @selectedprod = Bazesprod.where(id: params[:tocopy]).first
          Nevelprod.create({ :user_id => current_user.id, :prod_nos => @selectedprod.prodnos } )
          redirect_to nevelprods_path
        end
      end
    else
      redirect_to nevelprods_path, notice: "Jāizvēlas produkts"
    end
  end

  def correct_user
    @nevelprod = current_user.nevelprods.find_by(id: params[:id])
    redirect_to nevelprods_path, notice: "Nav tiesību rediģēt" if @nevelprod.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nevelprod
      @nevelprod = Nevelprod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nevelprod_params
      params.require(:nevelprod).permit(:user_id, :prod_nos)
    end
end

app/helpers/nevelprods_helper.rb
module NevelprodsHelper
end

app/views/nevelprods/_form.html.erb
<div class="row">
  <div class="col-4">
      <%= form_with(model: nevelprod) do |form| %>
        <% if nevelprod.errors.any? %>
          <br/>
          <div class="card">
            <h5 class="card-header"><%= I18n.t('errors.template.header', count: nevelprod.errors.count) %></h5>
            <div class="card-body">
              <div id="error_explanation">
              </div>
              <p class="card-text">
              <ul>
                <% nevelprod.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
              </p>
            </div>
          </div>
        <% end %>
    </div>
  </div>

  <div class="field">
    <% form.label :user_id %>
    <%= form.number_field :user_id, id: :nevelprods_user_id, value: current_user.id, type: :hidden  %>
  </div>
  <div class="row">
    <div class="col-4">
      <div class="form-control needs-validation">
        <div class="field">
          <%= form.label I18n.t(:prod_nos), class: "form-label" %>
          <%= form.text_field :prod_nos, class: "form-control", required: true%>
          <div class="invalid-feedback">
            Please choose a username.
          </div>
        </div>
        <br/>
        <div class="row justify-content-between">

          <div class="field">
            <% form.label :user_id %>
            <%= form.number_field :user_id, id: :nevelprods_user_id, value: current_user.id, type: :hidden  %>
          </div>
          <% if @type=="edit" %>
            <% submit_name = "Atjaunināt" %>
          <% else submit_name = "Pievienot"%>
          <% end %>
          <div class="row justify-content-between">
            <div class="col">
              <%= link_to 'Atpakaļ', nevelprods_path,class: "btn btn-secondary" %>
            </div>
            <div class="col-3">
              <%= form.submit submit_name, class: "btn btn-primary" %>
              <br/><br/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>





<% end %>

app/views/nevelprods/edit.html.erb
<h1></h1>
<%= render 'form', nevelprod: @nevelprod %>

app/views/nevelprods/index.html.erb
<br/>

<div class="container">


  <div class="row row-cols-3 ">
    <div class="col-5">
      <div class="card" style="width: 24rem;">
        <div class="card-body">
          <h1 class="card-title">Jūsu nevēlamo produktu saraksts</h1>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><%= I18n.t(:prodnos) %></th>
              </tr>
            </thead>
            <tbody>
              <% @nevelprods.each do |nevelprod| %>
                <% if current_user == nevelprod.user %>
                  <tr>
                    <td><%= nevelprod.prod_nos %></td>
                    <td><%= link_to 'Rediģēt', edit_nevelprod_path(nevelprod), class: "btn btn-primary btn-sm" %></td>
                    <td><%= link_to 'Noņemt', nevelprod, method: :delete, data: { confirm: 'Vai Jūs esat pārliecināti?' }, class: "btn btn-danger btn-sm" %></td>
                  </tr>
                <% end %>
              <% end %>

            </tbody>

          </table>
          <%= link_to 'Pievienot savu produktu', new_nevelprod_path, class: "btn btn-primary" %>

        </div>
        <br/>
        <%= link_to 'Uz galveni', lietotajaparametrs_path, class: "btn btn-secondary" %>
      </div>
    </div>

    <div class="col-4">
      <div class="form-control" style="margin-top:45px;">
        <%= form_with(url: '/nevelprods/adding', method: 'get') do |f| %>
          <div class="field">
            <h4><%= f.label "Izvēlēties un pievienot eksistējošo produktu:" %></h4>

            <%= f.select :tocopy, options_from_collection_for_select(@baze, 'id', 'prodnos'), {prompt: "Izvēlēties produktu" }, {class: "form-select" }  %>
            <br/>
            <%= f.submit "Pievienot produktu", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/nevelprods/new.html.erb
<h1>Pievienot nevēlāmo produktu</h1>

<%= render 'form', nevelprod: @nevelprod %>
<br/>