config/routes.rb
Rails.application.routes.draw do
  resources :edienkartes
  get 'lietotajaparametrs/activatepython'
  get 'velprods/test'
  get 'nevelprods/adding'
  get 'edienkartes/tested'
  get 'bazesprods/product'
  resources :bazesprods
  resources :velprods
  resources :nevelprods
  resources :lietotajaparametrs
  devise_for :users, controllers: { registrations: "registrations" }
  root 'lietotajaparametrs#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/velprod.rb
class Velprod < ApplicationRecord
  belongs_to :user
  validates :prod_nos, presence: true
  validates :olb, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :tauki, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :oglh, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :kcal, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :A, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :B1, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :B2, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :C, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :Ca, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :P, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :Fe, presence: true, format: { with: /\A([1-9]\d*|0)(\.\d+)?\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :cena, presence: true, format: { with: /\A(([0]|[1-9]+)(\.\d{1,2})?)\Z/, message: '- Ievadiet tikai vienu veselo skaitli vai decimalo skaitli' }
  validates :min, presence: true, format: { with: /\A([1-9]\d*|0)\Z/, message: '- Ievadiet tikai veselo skaitli' }
  validates :max, presence: true, format: { with: /\A([1-9]\d*)\Z/, message: '- Ievadiet tikai veselo skaitli' }



end

app/controllers/velprods_controller.rb
class VelprodsController < ApplicationController
  before_action :set_velprod, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /velprods or /velprods.json
  @type = 'any'
  def index
    @velprods = Velprod.all
    @baze = Bazesprod.order('prodnos ASC').all
  end

  # GET /velprods/1 or /velprods/1.json
  def show
  end

  # GET /velprods/new
  def new
    @velprod = current_user.velprods.build
  end

  # GET /velprods/1/edit
  def edit
    @type = 'edit'
  end

  # POST /velprods or /velprods.json
  def create
    @velprod = current_user.velprods.build(velprod_params)

    respond_to do |format|
      if @velprod.save
        format.html { redirect_to velprods_url, notice: "Produkts ir veiksmīgi pievienots." }
        format.json { render :show, status: :created, location: @velprod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @velprod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /velprods/1 or /velprods/1.json
  def update
    respond_to do |format|
      if @velprod.update(velprod_params)
        format.html { redirect_to velprods_url, notice: "Produkts ir veiksmīgi atjaunināts." }
        format.json { render :show, status: :ok, location: @velprod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @velprod.errors, status: :unprocessable_entity }
      end
    end
  end

  def test
    if params[:tocopy] != "" and params[:tocopy].to_i != 0  #defense from sql injection
      if !Bazesprod.exists?(params[:tocopy])
        redirect_to velprods_path, notice: "Jāievada eksistējošais produkts"
      else
        if Velprod.exists?(prod_nos: Bazesprod.where(id: params[:tocopy]).first.prodnos, user_id: current_user.id)
          redirect_to velprods_path, notice: "Izvēlētais produkts jau ir pievienots"
        else
          @selectedprod = Bazesprod.where(id: params[:tocopy]).first
          Velprod.create({:user_id => current_user.id, :prod_nos => @selectedprod.prodnos, :olb => @selectedprod.olb, :tauki => @selectedprod.tauki, :oglh => @selectedprod.oglh, :kcal => @selectedprod.kcal, :A => @selectedprod.A, :B1 => @selectedprod.B1, :B2 => @selectedprod.B2, :C => @selectedprod.C, :Ca => @selectedprod.Ca, :P => @selectedprod.P, :Fe => @selectedprod.Fe, :cena => @selectedprod.cena, :min => @selectedprod.min, :max => @selectedprod.max})
          redirect_to velprods_path
        end
      end
    else
      redirect_to velprods_path, notice: "Jāizvēlas produkts"
    end
  end

  # DELETE /velprods/1 or /velprods/1.json
  def destroy
    @velprod.destroy
    respond_to do |format|
      format.html { redirect_to velprods_url, notice: "Produkts ir veiksmīgi noņemts." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @nevelprod = current_user.velprods.find_by(id: params[:id])
    redirect_to velprods_path, notice: "Nav tiesību rediģēt" if @velprod.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_velprod
      @velprod = Velprod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def velprod_params
      params.require(:velprod).permit(:user_id, :prod_nos, :olb, :tauki, :oglh, :kcal, :A, :B1, :B2, :C, :Ca, :P, :Fe, :cena, :min, :max)
    end
end

app/helpers/velprods_helper.rb
module VelprodsHelper
end

app/views/velprods/_form.html.erb
<div class="row">
  <div class="col-4">
    <div class="form-control">
      <%= form_with(model: velprod) do |form| %>
        <% if velprod.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(velprod.errors.count, "error") %> prohibited this velprod from being saved:</h2>

            <ul>
              <% velprod.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <h1> <%= "#{velprod.prod_nos}" %> </h1>
        <div class="row">
          <div class="col">
            <% unless @type=='edit' %>
              <div class="field">
                <%= form.label I18n.t(:prod_nos), class: "form-label" %>
                <%= form.text_field :prod_nos, class: "form-control", required: true %>
              </div>
            <% end %>

            <div class="field">
              <%= form.label I18n.t(:olb), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :olb, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">g</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:tauki), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :tauki, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">g</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:oglh), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :oglh, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">g</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:kcal), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :kcal, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">kcal</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:A), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :A, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:B, num: 1), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :B1, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:B, num: 2), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :B2, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="field">
              <%= form.label I18n.t(:C), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :C, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:Ca), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :Ca, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:P), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :P, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:Fe), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :Fe, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">mg</span>
              </div>
            </div>

            <div class="field">
              <%= form.label :cena, class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :cena, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">€</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:min), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :min, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">g</span>
              </div>
            </div>

            <div class="field">
              <%= form.label I18n.t(:max), class: "form-label" %>
              <div class="input-group" >
                <%= form.number_field :max, step: :any, class: "form-control", required: true %>
                <span class="input-group-text">g</span>
              </div>
            </div>
          </div>
        </div>

        <div class="field">
          <% form.label :user_id %>
          <%= form.number_field :user_id, id: :velprods_user_id, value: current_user.id, type: :hidden  %>
        </div>
        <br/>
        <% if @type=="edit" %>
          <% submit_name = "Atjaunināt" %>
        <% else submit_name = "Pievienot"%>
        <% end %>

        <div class="row justify-content-between">
          <div class="col">
            <%= link_to 'Atpakaļ', velprods_path,class: "btn btn-secondary" %>
          </div>
          <div class="col-4">
            <%= form.submit submit_name, class: "btn btn-primary" %>
            <br/><br/>
          </div>
        </div>

      </div>
    </div>
  </div>


<% end %>

app/views/velprods/edit.html.erb
<%= render 'form', velprod: @velprod %>
<br/>

app/views/velprods/index.html.erb
<br/>

<div class="container">


<div class="row row-cols-3 ">
  <div class="col-5">
    <div class="card" style="width: 24rem;">
      <div class="card-body">
        <h1 class="card-title">Jūsu produktu saraksts</h1>
        <table class="table table-striped table-hover">
          <thead>
          <tr>

            <th><%= I18n.t(:prodnos) %></th>
          </tr>

          </thead>
          <tbody>
          <% @velprods.each do |velprod| %>
            <% if current_user == velprod.user %>
                <tr>
                  <td><%= velprod.prod_nos %></td>
                  <td><%= link_to 'Rediģēt', edit_velprod_path(velprod), class: "btn btn-primary btn-sm"%></td>

                  <td><%= link_to 'Noņemt', velprod, method: :delete, data: { confirm: 'Vai Jūs esat pārliecināti?' }, class: "btn btn-danger btn-sm" %></td>

                </tr>
            <% end %>
          <% end %>

          </tbody>

        </table>
        <%= link_to 'Pievienot savu produktu', new_velprod_path, class: "btn btn-primary" %>

      </div>
      <br/>
      <%= link_to 'Uz galveni', lietotajaparametrs_path, class: "btn btn-secondary" %>
    </div>
  </div>

    <div class="col-4">
      <div class="form-control" style="margin-top:45px;">
        <%= form_with(url: '/velprods/test', method: 'get') do |f| %>
        <div class="field">
          <h4><%= f.label "Izvēlēties un pievienot eksistējošo produktu:" %></h4>

          <%= f.select :tocopy, options_from_collection_for_select(@baze, 'id', 'prodnos'), {prompt: "Izvēlēties produktu" }, {class: "form-select" }  %>
          <br/>
          <%= f.submit "Pievienot produktu", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/velprods/new.html.erb
<h1>Pievienot produktu</h1>

<%= render 'form', velprod: @velprod %>

app/views/velprods/show.html.erb
<p>
  <strong>Prod nos:</strong>
  <%= @velprod.prod_nos %>
</p>



<%= link_to 'Edit', edit_velprod_path(@velprod) %> |
<%= link_to 'Back', velprods_path %>